---
title: "Flow Score Analysis"
author: "Julia Zielke"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidyr)
library(dplyr)

output_path = "plots/"
```

#import data
```{r}
df <- read.csv("score-analysis/data/score_analysis_flow.csv")
```

#coerce numeric
```{r}
df[] <- lapply(df, as.numeric) 

#reinstate NAs caused by numeric coercion
df <- df %>%
  mutate(condition = c("during", "after", "before"))

```
#bar graph
```{r}

#convert to long form for plot
library(reshape2)
df.long<-melt(df,id.vars="condition")

#calculate percent out of 34 melodies
df.long_percent <- df.long %>%
  mutate(percent = value/34 * 100)

score_bar_graph <- ggplot(df.long_percent, aes(x = variable, y = percent, fill = condition)) + 
  geom_bar(position = "dodge", stat = "identity", alpha = 0.7) + 
  #facet_wrap(~variable) +
  xlab("Feature") +
  ylab("Percent of excerpts") +
  ggtitle("Musical Feature Differences Between Before, During, and After Flow Excerpts") +
  theme(axis.text.x = element_blank()) +
  theme_classic()

score_bar_graph

# save
ggsave(paste0(output_path, "Figure 5a.tiff"), 
       score_bar_graph, 
       height = 5, width = 9,
       units = "cm",
       dpi=300)


```

